# Court Line Constants
SINGLES_LINE_WIDTH = 8.23
DOUBLES_LINE_WIDTH = 10.97
HALF_COURT_LINE_HEIGHT = 11.88
SERVICE_LINE_WIDTH = 6.4
DOUBLES_ALLEY_DIFFERENCE = 1.37
NO_MANS_LAND_HEIGHT = 5.48

# Player Constants
DJOKOVIC_HEIGHT_IN_METERS = 1.88
SONENGO_HEIGHT_IN_METERS = 1.91


